import type { Booking, Room, Client, Coupon, Contract } from "./types"

export const initialBookings: Booking[] = [
  {
    id: "REQ-2026-001",
    company: "Unimed Piracicaba",
    room: "Auditorio + Foyer",
    date: "15/04/2026",
    time: "08:00 - 18:00",
    value: "R$ 3.450,00",
    status: "Pendente",
    contract: "Pendente",
    companyData: {
      razaoSocial: "Unimed Piracicaba Cooperativa de Trabalho Medico",
      nomeFantasia: "Unimed Piracicaba",
      cnpj: "43.344.555/0001-22",
      ie: "Isento",
      cep: "13414-000",
      endereco: "Av. Carlos Botelho",
      numero: "1000",
      complemento: "Bloco A",
      bairro: "Sao Dimas",
      cidade: "Piracicaba",
      estado: "SP",
    },
    responsavelData: {
      nome: "Carlos Eduardo Mendes",
      email: "carlos.mendes@unimedpiracicaba.com.br",
      telefone: "(19) 99999-1234",
      cargo: "Diretor de Eventos",
    },
    eventoData: {
      nome: "Simposio de Inovacao Medica",
      finalidade: "Apresentar novas tecnologias para cooperados",
      participantes: 150,
      responsavelDia: "Mariana Souza",
      contatoDia: "(19) 98888-5555",
      pagamento: "Boleto",
      infoAdicional: "Projetor extra, 3 microfones de lapela.",
    },
    financeiroData: {
      valorBase: "R$ 4.500,00",
      descontoAssociado: "R$ 1.350,00 (30%)",
      cupom: "Nenhum",
      descontoCupom: "R$ 0,00",
    },
  },
  {
    id: "REQ-2026-002",
    company: "Drogal Farmaceutica",
    room: "Sala de Reunioes 1",
    date: "12/04/2026",
    time: "14:00 - 16:00",
    value: "R$ 450,00",
    status: "Confirmada",
    contract: "Assinado",
    companyData: {
      razaoSocial: "Rede Drogal Ltda",
      nomeFantasia: "Drogal Farmaceutica",
      cnpj: "12.345.678/0001-99",
      ie: "123.456.789.000",
      cep: "13400-000",
      endereco: "Rua Governador",
      numero: "500",
      complemento: "",
      bairro: "Centro",
      cidade: "Piracicaba",
      estado: "SP",
    },
    responsavelData: {
      nome: "Ana Clara Silva",
      email: "ana.silva@drogal.com.br",
      telefone: "(19) 97777-4444",
      cargo: "Gerente de RH",
    },
    eventoData: {
      nome: "Reuniao de Diretoria",
      finalidade: "Planejamento Estrategico",
      participantes: 12,
      responsavelDia: "Ana Clara Silva",
      contatoDia: "(19) 97777-4444",
      pagamento: "Cartao de Credito",
      infoAdicional: "Nenhuma.",
    },
    financeiroData: {
      valorBase: "R$ 562,50",
      descontoAssociado: "R$ 112,50 (20%)",
      cupom: "Nenhum",
      descontoCupom: "R$ 0,00",
    },
  },
]

export const initialRooms: Room[] = [
  {
    id: 1,
    name: "Auditorio Principal",
    capacity: 199,
    priceDay: "350.00",
    priceWeekend: "450.00",
    minHours: 4,
    minHoursWeekend: 4,
    status: "Disponivel",
    img: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&q=80&w=400&h=250",
    amenities: ["Wi-Fi", "Projetor", "Sistema de Som"],
  },
  {
    id: 2,
    name: "Foyer",
    capacity: 100,
    priceDay: "150.00",
    priceWeekend: "200.00",
    minHours: 2,
    minHoursWeekend: 4,
    status: "Disponivel",
    img: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&q=80&w=400&h=250",
    amenities: ["Cafe/Copa", "Wi-Fi"],
  },
  {
    id: 3,
    name: "Sala de Reunioes 1",
    capacity: 15,
    priceDay: "100.00",
    priceWeekend: "150.00",
    minHours: 2,
    minHoursWeekend: 2,
    status: "Manutencao",
    img: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=400&h=250",
    amenities: ["TV/Monitor", "Videoconferencia"],
  },
]

export const initialClients: Client[] = [
  {
    cnpj: "43.344.555/0001-22",
    name: "Unimed Piracicaba",
    plano: "Plano Saude Ouro",
    lucro: "35%",
    email: "eventos@unimedpiracicaba.com.br",
    phone: "(19) 3434-0000",
    totalBookings: 12,
    totalSpent: "R$ 38.500,00",
    associado: true,
    meses: 48,
  },
  {
    cnpj: "12.345.678/0001-99",
    name: "Drogal Farmaceutica",
    plano: "N/A",
    lucro: "20%",
    email: "rh@drogal.com.br",
    phone: "(19) 3422-1111",
    totalBookings: 5,
    totalSpent: "R$ 4.250,00",
    associado: true,
    meses: 14,
  },
]

export const initialCoupons: Coupon[] = [
  { id: 1, code: "ACIPITECH10", type: "percentage", value: 10, maxUses: 100, currentUses: 45, validUntil: "2026-12-31", active: true },
  { id: 2, code: "BEMVINDO50", type: "fixed", value: 50, maxUses: "", currentUses: 312, validUntil: "", active: true },
  { id: 3, code: "INVERNO20", type: "percentage", value: 20, maxUses: 50, currentUses: 50, validUntil: "2026-08-30", active: false },
]

export const initialContracts: Contract[] = [
  { id: "CTR-2026-001", bookingId: "REQ-2026-003", company: "Caterpillar Brasil", date: "09/04/2026", status: "Enviado para Assinatura" },
  { id: "CTR-2026-002", bookingId: "REQ-2026-002", company: "Drogal Farmaceutica", date: "05/04/2026", status: "Assinado" },
]

export const ALL_AMENITIES = [
  "Wi-Fi",
  "Ar Condicionado",
  "Projetor",
  "TV/Monitor",
  "Quadro Branco",
  "Sistema de Som",
  "Cafe/Copa",
  "Videoconferencia",
  "Estacionamento",
]
